In [12]:
#BOY KİLO YAŞ İLE CİNSİYET TAHMİN EDEN MODEL GLEİŞTİRİYORUZ. 


#1.kutuphaneler
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#2.veri onisleme
#2.1.veri yukleme

veriler = pd.read_csv('veriler.csv')

#pd.read_csv("veriler.csv")
#test


x = veriler.iloc[:,1:4].values #bağımsız değişkenler
y = veriler.iloc[:,4:].values #bağımlı değişken


#verilerin egitim ve test icin bolunmesi
from sklearn.model_selection import train_test_split

x_train, x_test,y_train,y_test = train_test_split(x,y,test_size=0.33, random_state=0)



#verilerin olceklenmesi
from sklearn.preprocessing import StandardScaler

sc=StandardScaler()
X_train = sc.fit_transform(x_train) #fit eğit, transform o öğrendiğini kullan 
X_test = sc.transform(x_test)
print(X_test)
print('-------------------------------------------')


#logistic regression 
from sklearn.linear_model import LogisticRegression
logr = LogisticRegression(random_state=0)
logr.fit(X_train,y_train)

y_pred = logr.predict(X_test)
print(y_pred)
print('----------------------------------')
print(y_test)#X_testin gerçek sonuçları 

#tahmin ettik ama yanlış sonuç verdi hepsini, bu konu hakkında konuşacağız. 
#--------------------------------------

#CONFUSION MATRİX TANIMI
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred) #test ile prediction arasında bir matrix oluştur. 
print(cm)

'''
iki tane sınıf var 
[[0 1]
 [7 0]]
0ve0 doğru 
1ve7 yanlış 
''' 
#outlier lar sistemin çalışmasını engelliyorlar. parazit gibi bir şey
#-------------------------------------
#KNN !
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1, metric='minkowski') #parametre vericemi komşu defoultu 5   
#neighbors sayısını azalttık ve matrixde sonuç inanılmaz değişti. 
knn.fit(X_train,y_train)
y_pred = knn.predict(X_test)
#Buradan sonra confision matrixi kullanacam.
cm = confusion_matrix(y_test,y_pred) #test için ayırdığım ile, tahmin ettiğim şey 
print(cm)
#KNN İLE CONFİSİON MATRİXDEKİ DOĞRU SAYIMIZ 7 MİSLİ ARTTI, BİR ÖNCEKİ CONFİSİON MATRİXİNİ LOGİSTİC REGRESSİON İLE YAPMIŞTIK.

















[[-0.10726058 -0.05470872  0.6225517 ]
 [-0.06435635 -0.49813728  0.17787191]
 [ 0.02145212 -0.21595547  2.66807872]
 [-0.19306904 -0.33689053  1.42297532]
 [-1.78052563 -1.26405934 -1.2451034 ]
 [-0.02145212 -0.45782559  1.51191128]
 [-0.49339867 -0.69969571  1.68978319]
 [-0.32178174 -1.10281259  0.35574383]]
-------------------------------------------
['e' 'e' 'e' 'e' 'k' 'e' 'e' 'e']
----------------------------------
[['k']
 ['k']
 ['k']
 ['k']
 ['e']
 ['k']
 ['k']
 ['k']]
[[0 1]
 [7 0]]
[[1 0]
 [1 6]]


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:179: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


In [19]:
veriler

ulke  boy  kilo  yas cinsiyet
0    tr  130    30   10        e
1    tr  125    36   11        e
2    tr  135    34   10        k
3    tr  133    30    9        k
4    tr  129    38   12        e
5    tr  180    90   30        e
6    tr  190    80   25        e
7    tr  175    90   35        e
8    tr  177    60   22        k
9    us  185   105   33        e
10   us  165    55   27        k
11   us  155    50   44        k
12   us  160    58   39        k
13   us  162    59   41        k
14   us  167    62   55        k
15   fr  174    70   47        e
16   fr  193    90   23        e
17   fr  187    80   27        e
18   fr  183    88   28        e
19   fr  159    40   29        k
20   fr  164    66   32        k
21   fr  166    56   42        k