In [40]:
#1. kutuphaneler
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#2. Veri Onisleme
#2.1. Veri Yukleme
veriler = pd.read_csv('odev_tenis.csv')
#pd.read_csv("veriler.csv")

#veri on isleme
#encoder:  Kategorik -> Numeric
from sklearn.preprocessing import LabelEncoder
veriler2 = veriler.apply(LabelEncoder().fit_transform)#bütün kolonlara apply et fittransformu 
c = veriler2.iloc[:,:1]#outlook kolunu 

from sklearn.preprocessing import OneHotEncoder
ohe= OneHotEncoder()
c = ohe.fit_transform(c).toarray()
print(c)

havadurumu = pd.DataFrame(data=c, index=range(14), columns=['o','r','s'])
sonveriler = pd.concat([havadurumu,veriler.iloc[:,1:3]],axis = 1)
sonveriler = pd.concat([veriler2.iloc[:,-2:],sonveriler], axis = 1)
print(sonveriler)
#veri ön işleme bittiii 


#verilerin egitim ve test icin bolunmesi
from sklearn.model_selection import train_test_split
x_train, x_test,y_train,y_test = train_test_split(sonveriler.iloc[:,:-1],sonveriler.iloc[:,-1:],test_size=0.33, random_state=0)#hepsi vs play or not
#üst kodda; sonveriler dataframesindeki son kolon hariç bütün kolonları istiyorum test için diyor, çünkü son kolon bağımlı değişken 

from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train,y_train)
y_pred = regressor.predict(x_test)
print(y_pred)




#aşağısı hatalı kod. 



#backward elimination
import statsmodels.formula.api as sm 
X = np.append(arr = np.ones((14,1)).astype(int), values=sonveriler.iloc[:,:-1], axis=1)#!!!!!!!!!!!!!
X_l = sonveriler.iloc[:,[0,1,2,3,4,5]].values#bağımsız değişkenlerim 
r_ols = sm.ols(endog = sonveriler.iloc[:,-1:], exog =X_l) # sırasıyla bağımlı ve bağımsız değişkenim 
r = r_ols.fit()
print(r.summary())

sonveriler = sonveriler.iloc[:,1:]

import statsmodels.formula.api as sm 
X = np.append(arr = np.ones((14,1)).astype(int), values=sonveriler.iloc[:,:-1], axis=1 )
X_l = sonveriler.iloc[:,[0,1,2,3,4]].values
r_ols = sm.ols(endog = sonveriler.iloc[:,-1:], exog =X_l)
r = r_ols.fit()
#print(r.summary())

x_train = x_train.iloc[:,1:]  #beğenmediğimiz kolonu değiştiriyoruz. 
x_test = x_test.iloc[:,1:]
regressor.fit(x_train,y_train)# ardından yeniden bir öğretme veee

y_pred = regressor.predict(x_test)#vee tahminn 
print(y_pred)


[[0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]
    windy  play    o    r    s  temperature  humidity
0       0     0  0.0  0.0  1.0           85        85
1       1     0  0.0  0.0  1.0           80        90
2       0     1  1.0  0.0  0.0           83        86
3       0     1  0.0  1.0  0.0           70        96
4       0     1  0.0  1.0  0.0           68        80
5       1     0  0.0  1.0  0.0           65        70
6       1     1  1.0  0.0  0.0           64        65
7       0     0  0.0  0.0  1.0           72        95
8       0     1  0.0  0.0  1.0           69        70
9       0     1  0.0  1.0  0.0           75        80
10      1     1  0.0  0.0  1.0           75        70
11      1     1  1.0  0.0  0.0           72        90
12      0     1  1.0  0.0  0.0           81        75
13      1     0  0.0  1.0  0.0           71        91
[[84.45365573]
 [63.9

TypeError: from_formula() missing 2 required positional arguments: 'formula' and 'data'