In [2]:
#BOY KİLO YAŞ İLE CİNSİYET TAHMİN EDEN MODEL GLEİŞTİRİYORUZ. 


#1.kutuphaneler
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#2.veri onisleme
#2.1.veri yukleme

veriler = pd.read_csv('veriler.csv')

#pd.read_csv("veriler.csv")
#test


x = veriler.iloc[:,1:4].values #bağımsız değişkenler
y = veriler.iloc[:,4:].values #bağımlı değişken


#verilerin egitim ve test icin bolunmesi
from sklearn.model_selection import train_test_split

x_train, x_test,y_train,y_test = train_test_split(x,y,test_size=0.33, random_state=0)



#verilerin olceklenmesi
from sklearn.preprocessing import StandardScaler

sc=StandardScaler()
X_train = sc.fit_transform(x_train) #fit eğit, transform o öğrendiğini kullan 
X_test = sc.transform(x_test)
print(X_test)
print('-------------------------------------------')


#logistic regression 
from sklearn.linear_model import LogisticRegression
logr = LogisticRegression(random_state=0)
logr.fit(X_train,y_train)

y_pred = logr.predict(X_test)
print(y_pred)
print('----------------------------------')
print(y_test)#X_testin gerçek sonuçları 

#tahmin ettik ama yanlış sonuç verdi hepsini, bu konu hakkında konuşacağız. 
#--------------------------------------

#CONFUSION MATRİX TANIMI
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred) #test ile prediction arasında bir matrix oluştur. 
print(cm)

#KNN !
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1, metric='minkowski') #parametre vericemi komşu defoultu 5   
#neighbors sayısını azalttık ve matrixde sonuç inanılmaz değişti. 
knn.fit(X_train,y_train)
y_pred = knn.predict(X_test)
#Buradan sonra confision matrixi kullanacam.
cm = confusion_matrix(y_test,y_pred) #test için ayırdığım ile, tahmin ettiğim şey 
print(cm)

from sklearn.svm import SVC  # SUPPORT VECTOR CLASSİFİCATİON 
svc = SVC(kernel = 'rbf') #regresyondaki lineer polinomial vs yazdığımız parametrenin adı kernel idi.
#linear ile doğrsular bir ayrım arayacak 
svc.fit(X_train,y_train)
y_pred = svc.predict(X_test)

cm = confusion_matrix(y_test,y_pred)
print('SVC')
print(cm)


#naive bayes 

from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()  

gnb.fit(x_train,y_train)
y_pred = gnb.predict(X_test)
print('GMB')
cm = confusion_matrix(y_test,y_pred)
print(cm)



# #DECISION TREE 
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier(criterion='entropy') 
dtc.fit(X_train,y_train)
y_pred = dtc.predict(X_test)
print('dtc')
cm = confusion_matrix(y_test,y_pred)
print(cm)


#random forest 
# n_estimators = kaç tane ağaç oluşturacağım 

from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators=10, criterion='entropy')

rfc.fit(X_train,y_train)
y_pred= rfc.predict(X_test)

print('RFC')
cm = confusion_matrix(y_test,y_pred)#önce doğrular sonra tahminler 
print(cm)











[[-0.10726058 -0.05470872  0.6225517 ]
 [-0.06435635 -0.49813728  0.17787191]
 [ 0.02145212 -0.21595547  2.66807872]
 [-0.19306904 -0.33689053  1.42297532]
 [-1.78052563 -1.26405934 -1.2451034 ]
 [-0.02145212 -0.45782559  1.51191128]
 [-0.49339867 -0.69969571  1.68978319]
 [-0.32178174 -1.10281259  0.35574383]]
-------------------------------------------
['e' 'e' 'e' 'e' 'k' 'e' 'e' 'e']
----------------------------------
[['k']
 ['k']
 ['k']
 ['k']
 ['e']
 ['k']
 ['k']
 ['k']]
[[0 1]
 [7 0]]
[[1 0]
 [1 6]]
SVC
[[1 0]
 [5 2]]
GMB
[[1 0]
 [7 0]]
dtc
[[1 0]
 [1 6]]
RFC
[[0 1]
 [2 5]]


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:179: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example u